[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = {version="4.2.1", features=["rustls"]}
tokio = {version = "1", features=["macros", "rt-multi-thread"]}
